### ISSUE TITLE
검색엔진 구현방안 리서치

### ISSUE THREAD

**Issue by goinhacker** [funfunStudy/funfunnet#26]
검색엔진 구현방안에 대한 리서치를 진행하고 공유합니다.

검색엔진 구현방안이란 tagging 사용한 검색등의 지원하는 라이브러리나 프레임워크을 조사하고 어떤 것이 적합할지 찾는 과정입니다.

예를들어 elastic search 같은 검색엔진은 어떤 것들이 있는지와 각각의 장단점, 주로 언제 사용되는지 등에 대해서 조사하면 됩니다.

**Comment by insford** [comment]
엘라스틱 서치의 간단한 구조 및 장단점

**Comment by insford** [comment]
간단하게 위키에다 정리했습니다.
https://github.com/funfunStudy/funfunnet/wiki/SearchEngine-Research
