### ISSUE TITLE
Play Batch Processing 구현

### ISSUE THREAD

**Issue by goinhacker** [funfunStudy/funfunnet#32]
funfun-crawler에 Batch Processing 설정하기

일단 정책은 1시간에 한번씩 도는 것으로.. 

참고. 
Akka Scheduler 활용(http://doc.akka.io/docs/akka/2.5.3/scala/scheduler.html)
Akka Stream 활용(http://doc.akka.io/docs/akka/2.5.3/scala/stream/stream-quickstart.html#time-based-processing)
https://github.com/apache/flink

**Comment by insford** [comment]
akka single application 으로 진행해봄
